# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "CI"

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  NANOBENCH_SUPPRESS_WARNINGS: 1
  TZ: Europe/Berlin

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, compiler: spdx_reuse_lint}
          - {os: ubuntu-22.04, compiler: cpm_version_check}
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction@v9.3
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cmake_flags: ${{ matrix.cmake_flags }}
