# SPDX-FileCopyrightText: 2024 Simon Gene Gottlieb
# SPDX-License-Identifier: CC0-1.0
name: Publish Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  TZ: Europe/Berlin

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install -U jq yq
          ./scripts/convert.sh > docs/lines.md
      - run: pip install mkdocs-material mkdocs-include-markdown-plugin
      - run: TZ=UTC mkdocs gh-deploy --force
