# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "On PullRequest"

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  TZ: Europe/Berlin

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
#          - {os: ubuntu-22.04, compiler: spdx_license_lint}
          - {os: ubuntu-22.04, compiler: gcc13-cpp20-release}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
          submodules: recursive
          fetch-tags: true

      - name: Check changed folders
        if: ${{ matrix.compiler }} != 'spdx_license_lint'
        shell: bash
        run: |-
          cd repo
          git status
          git fetch
          git log -n 1 origin/${GITHUB_BASE_REF}
          #git log -n 1 origin/${GITHUB_REF_NAME}
          git log -n 1 HEAD
          files=$(git diff --name-only origin/${GITHUB_BASE_REF}..HEAD)
          echo $files

      - name: Check license files
        if: ${{ matrix.compiler }} == 'spdx_license_lint'
        uses: iv-project/IVaction@v10.3
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cmake_flags: ${{ matrix.cmake_flags }}
  final:
    runs-on: ubuntu-22.04
    name: final-pass
    needs: build
    if: always()
    steps:
      - name: Succeeded
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: CI failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
